#!/usr/bin/env python3
"""Convert browser cookie table export to Netscape format for yt-dlp."""
import sys
from datetime import datetime

def convert_timestamp(ts_str):
    """Convert ISO timestamp to Unix timestamp."""
    if ts_str == 'Session':
        return 0
    try:
        return int(datetime.fromisoformat(ts_str.replace('Z', '+00:00')).timestamp())
    except:
        return 0

def main():
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    youtube_cookies = []
    other_cookies = []
    
    with open(input_file, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            parts = line.split('\t')
            if len(parts) < 7:
                continue
            
            # Browser export format (12 columns):
            # [0] name, [1] value, [2] domain, [3] path, [4] expiration (ISO),
            # [5] size, [6-7] flags (✓), [8] sameSite, [9] sourceScheme, [10] sourcePort, [11] priority
            
            name = parts[0]
            value = parts[1]
            domain = parts[2]
            path = parts[3]
            expiration = parts[4]
            
            exp = convert_timestamp(expiration)
            
            # Determine secure flag
            secure = 'TRUE'
            
            if '.youtube.com' in domain or 'youtube.com' in domain:
                youtube_cookies.append(
                    f'{domain}\t{"TRUE" if domain.startswith(".") else "FALSE"}\t{path}\t{secure}\t{exp}\t{name}\t{value}'
                )
            else:
                other_cookies.append(
                    f'{domain}\t{"TRUE" if domain.startswith(".") else "FALSE"}\t{path}\t{secure}\t{exp}\t{name}\t{value}'
                )
    
    with open(output_file, 'w') as f:
        f.write('# Netscape HTTP Cookie File\n')
        f.write('# This file is generated by yt-dlp.  Do not edit.\n\n')
        
        for c in youtube_cookies:
            f.write(c + '\n')
        
        for c in other_cookies:
            f.write(c + '\n')
    
    print(f'Converted {len(youtube_cookies)} YouTube cookies and {len(other_cookies)} other cookies')
    print(f'Output: {output_file}')

if __name__ == '__main__':
    main()
